#! /usr/bin/env python

import sys
import re
import argparse
import textwrap

REINDENT = re.compile('^(\s*[^\w\s]\s*)')
REWORDS = re.compile('\S+|^\s*')

def wrap(body, width):
    # Check indent
    m = REINDENT.match(body)
    if m:
        indent = ' ' * len(m.group())
    else:
        indent = ''

    # Arrange words in lines
    words = REWORDS.findall(body)
    line = words[0]
    if not indent:
        line += ' '
    first = True
    lines = []
    for w in words[1:]:
        if first:
            if len(line) + len(w) < width:
                # TODO Take the extra space into account?
                line += w + ' '
            else:
                lines.append(line)
                first = False
                line = w + ' '
        else:
            if len(indent) + len(line) + len(w) < width:
                # TODO Take the extra space into account?
                line += w + ' '
            else:
                lines.append(indent + line)
                line = w + ' '

    if first:
        lines.append(line)
    else:
        lines.append(indent + line)

    return lines

def main():
    # Arguments
    p = argparse.ArgumentParser()
    p.add_argument('width', nargs='?', type=int, default=80)
    args = p.parse_args()

    # Input
    body = sys.stdin.read()

    # Wrap
    print '\n'.join(wrap(body, args.width))

if __name__ == '__main__':
    sys.exit(main())
