#! /usr/bin/env python

import sys, re, argparse, textwrap

REINDENT = re.compile('^(\s*)([^\w\s]\s*)')
REWORDS = re.compile('\S+')

def wrap(body, width):
    # Check indent
    m = REINDENT.match(body)
    if m:
        firstindent, bullet =  m.groups()
        indent = ' ' * len(firstindent + bullet)
    else:
        firstindent, indent = '', ''

    # Arrange words in lines
    words = REWORDS.findall(body)
    line, first, lines = firstindent, True, []
    for w in words:
        if first:
            if len(line) + len(w) < width:
                # TODO Take the extra space into account?
                line += w + ' '
            else:
                lines.append(line)
                first = False
                line = w + ' '
        else:
            if len(indent) + len(line) + len(w) < width:
                # TODO Take the extra space into account?
                line += w + ' '
            else:
                lines.append(indent + line)
                line = w + ' '

    if first:
        lines.append(line)
    else:
        lines.append(indent + line)

    return lines

def main():
    # Arguments
    p = argparse.ArgumentParser()
    p.add_argument('width', nargs='?', type=int, default=80)
    args = p.parse_args()

    # Input
    body = sys.stdin.read()

    # Wrap
    print '\n'.join(wrap(body, args.width))

if __name__ == '__main__':
    sys.exit(main())
